pyuic4 src/Gui/Main_window.ui     -o src/Gui/Main_window.py
pyuic4 src/Gui/mNewItem.ui        -o src/Gui/mNewItem.py
pyuic4 src/Gui/mNewReader.ui      -o src/Gui/mNewReader.py
pyuic4 src/Gui/mLoanReturnBook.ui -o src/Gui/mLoanReturnBook.py
pyuic4 src/Gui/mSearch.ui         -o src/Gui/mSearch.py
pyuic4 src/Gui/MainPage.ui        -o src/Gui/mMainPage.py
pyuic4 src/Gui/mLoanInfo.ui       -o src/Gui/mLoanInfo.py
pyuic4 src/Gui/mReaderInfo.ui     -o src/Gui/mReaderInfo.py
pyrcc4 src/Gui/myicons.qrc        -o src/Gui/myicons_rc.py
